name: Flutter Tag Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  run-flutter-tag-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ github.ref_name }}
      inventory-report-url: "https://tnremdeskapi.pxy2.tatnefturs.ru/api/v1/report"

  run-flutter-tag-cashdesk-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ format('{0}-cashdesk', github.ref_name) }}
      artifact-prefix: "cashdesk-"
      conn-type: "incoming"
      desktop-ui-flavor: "cashdesk"
      inventory-report-url: "https://tnremdeskapi.pxy2.tatnefturs.ru/api/v1/report"
